version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8
    environment:
      - MYSQL_PASSWORD=guest
      - MYSQL_USER=guest
      - MYSQL_DATABASE=exercise
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306    